package ntu.ce2006.swensens.hdbdesirabilityapp.search.filters;

/**
 * Created by trollpc on 20/03/17.
 */

public enum Location {
    ANG_MO_KIO, BEDOK, BISHAN, BUKIT_BATOK, BUKIT_MERAH, CHUA_CHU_KANG, CENTRAL_AREA,
    BUKIT_TIMAH, BUKIT_PANJANG, CLEMENTI, GEYLANG, HOUGANG, JURONG_EAST, JURONG_WEST,
    KALLANG_WHAMPOA, MARINE_PARADE, PASIR_RIS, PUNGGOL, QUEENSTOWN, SEMBAWANG, SENGKANG,
    SERANGOON, TAMPINES, TOA_PAYOH, WOODLANDS, YISHUN;
}
